### ISSUE TITLE
跑 npm run dev & npm run serve时报错

### ISSUE THREAD

**Issue by TonyLuo** [yuzai/weex-yanxuan#1]
![image](https://user-images.githubusercontent.com/3250305/32153732-47b6a0c0-bcfa-11e7-8804-114c2dd1c528.png)

```
ERROR in index.web.js from UglifyJs
Unexpected token: name (utilFunc) [index.web.js:2302,4]

ERROR in App.web.js from UglifyJs
Unexpected token: name (utilFunc) [App.web.js:2302,4]

ERROR in page/web.web.js from UglifyJs
Unexpected token: name (utilFunc) [page/web.web.js:2302,4]
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 963 bytes [entry]
         + 1 hidden modules
webpack: Failed to compile.
```

**Comment by yuzai** [comment]
weex的版本看一下，然后src下的文件不能有index.vue或者index.js

**Comment by yuzai** [comment]
直接copy的话要weex的版本和我的一样，我把版本信息加到readme了

**Comment by TonyLuo** [comment]
太坑了吧，连开发工具的版本都有要求？岂不是不能升级weex版本？
 $ weex -v
   v1.1.0-beta.5
 - weexpack : v0.4.7-beta.13
 - weex-builder : v0.2.13-beta.2
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.7

**Comment by yuzai** [comment]
不同版本真心不太一样，可以直接weex create然后复制之前那个人的src和assets文件试试，再根据情况修改webpack.config.js文件，主要是入口文件
